---
## PostDelete Hook: Räumt bei Bedarf übriggebliebene Ressourcen auf (Hier nur Textmeldung)
apiVersion: batch/v1
kind: Job
metadata:
  name: postdelete-audit
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: logger
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Warte 30 Sekunden bevor Audit-Log geschrieben wird …"
              sleep 30
              echo "Argo CD hat die Anwendung »sync-waves« am $(date -u +'%Y-%m-%dT%H:%M:%SZ') vollständig entfernt."
              sleep 10
  backoffLimit: 1
