---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: sync-waves
  annotations:
    #argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-wave: "3" # falsche reihenfolge um error zu erzeugen
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: quay.io/redhatdemo/openshift-pgsql12-primary:centos7
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: PG_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
            - name: PG_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: PG_DATABASE
              value: todo
            - name: PG_NETWORK_MASK
              value: all

