apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: sync-waves
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=