
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncfail-cleaner
  namespace: sync-waves
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: syncfail-cleaner
  namespace: sync-waves
rules:
  - apiGroups: [""]
    resources:
      - services
      - serviceaccounts
      - configmaps
      - secrets
      - pods
      - persistentvolumeclaims
    verbs: ["get", "list", "delete", "deletecollection"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "delete", "deletecollection"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "delete", "create", "deletecollection"]
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs: ["get", "list", "delete", "deletecollection"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - rolebindings
      - roles
    verbs: ["get", "list", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncfail-cleaner
  namespace: sync-waves
subjects:
  - kind: ServiceAccount
    name: syncfail-cleaner
    namespace: sync-waves
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: syncfail-cleaner
