apiVersion: batch/v1
kind: Job
metadata:
  name: todo-insert
  namespace: sync-waves
  annotations:
    argocd.argoproj.io/hook: PostSync # <1>
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded  # Löschung nach Erfolg
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation  # default, wenn nicht gesetzt: Hook bleibt bestehen bis der nächste erzeugt wird
spec:
  ##deaktiviert, damit der Job zu Debug-Zwecken bestehen bleibt, wenn "argocd.argoproj.io/hook-delete-policy: BeforeHookCreation" gesetzt
  #ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: httpie
          image: alpine/httpie:2.4.0
          imagePullPolicy: Always
          command: ["http"]
          args:
            [
              "POST",
              "todo-gitops:8080/api",
              "title=Finish ArgoCD tutorial",
              "--ignore-stdin"
            ]
      restartPolicy: Never
  backoffLimit: 1
